project:
  type: website
  output-dir: _site
  render:
    - "BirthAndLifeUniverse/birth_and_life_one_universe.qmd"
    - "WaveOrParticle/two_targets_qft_particle_wave_with_applet.qmd"
  resources:
    - ".nojekyll"
    - "index.html"
    - "shared/reveal/**"
    - "BirthAndLifeUniverse/assets/figures/**"
    - "BirthAndLifeUniverse/bbn-game/bbn_applet.html"
    - "BirthAndLifeUniverse/bbn-game/css/**"
    - "BirthAndLifeUniverse/bbn-game/data/**"
    - "BirthAndLifeUniverse/bbn-game/js/**"
    - "BlackHoles/BlackHoles.pdf"
    - "DarkMatter/DarkMatter.pdf"
    - "ModernPhysics/Lecture1.pdf"
    - "ModernPhysics/Lecture2.pdf"
    - "ModernPhysics/Lecture3.pdf"
    - "ModernPhysics/Lecture4.pdf"
    - "in-a-nutshell/index.html"
    - "in-a-nutshell/catalog.js"
    - "in-a-nutshell/HowDoWeKnowAboutAtoms.pdf"
    - "in-a-nutshell/InsideNucleus.pdf"
    - "in-a-nutshell/Matter.pdf"
    - "in-a-nutshell/WhatIsAtom.pdf"
    - "neutrino-telescope-astrofest-2026/NeutrinoTelescopes.pdf"

website:
  search: false

format:
  html:
    include-after-body:
      - text: |
          <script defer src="https://neutrinohit.github.io/assets/analytics/cloudflare-web-analytics.js"></script>
